version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: rps-postgres
    environment:
      POSTGRES_USER: rps_user
      POSTGRES_DB: rps_db
      POSTGRES_PASSWORD: rps_pass
    ports:
      - "5433:5432"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U rps_user -d rps_db"]
      interval: 5s
      retries: 5
